### ISSUE TITLE
No recovery from poor network connections

### ISSUE THREAD

**Issue by mceachen** [google/cups-connector#40] opened 2015-08-10 05:06 UTC
First off, thanks for writing this CUPS connector, it works perfectly with a decent network connection!

It looks like xmpp connections are being retried, but subsequent print jobs don't actually go though until the process is killed and restarted when network connections are spotty.

Here's the `nohup.out` of the borked process:

```
E0804 04:40:13.548336    5595 connector.go:32] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
E0804 04:40:33.219619    5595 connector.go:74] Ready to rock as proxy 'pi'
Ready to rock as proxy 'pi'
E0804 06:46:27.466277    5595 xmpp.go:130] XMPP conversation died; restarting
E0804 18:41:57.646329    5595 xmpp.go:130] XMPP conversation died; restarting
E0805 01:39:26.423607    5595 xmpp.go:130] XMPP conversation died; restarting
E0806 10:21:02.550903    5595 xmpp.go:130] XMPP conversation died; restarting
F0806 10:21:22.582713    5595 xmpp.go:132] Failed to keep XMPP conversation alive: While starting XMPP, failed to get access token (password): Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com: no such host
goroutine 18 [running]:
github.com/golang/glog.stacks(0x489400, 0x0, 0x0, 0x0)
	/home/pi/go/src/github.com/golang/glog/glog.go:769 +0xdc
github.com/golang/glog.(*loggingT).output(0x4852f8, 0x3, 0x96582b40, 0x45920a, 0x7, 0x84, 0x0)
	/home/pi/go/src/github.com/golang/glog/glog.go:720 +0x2bc
github.com/golang/glog.(*loggingT).printf(0x4852f8, 0x3, 0x35fad8, 0x2a, 0x9689bf74, 0x1, 0x1)
	/home/pi/go/src/github.com/golang/glog/glog.go:655 +0x1e8
github.com/golang/glog.Fatalf(0x35fad8, 0x2a, 0x9689bf74, 0x1, 0x1)
	/home/pi/go/src/github.com/golang/glog/glog.go:1148 +0x54
github.com/google/cups-connector/xmpp.(*XMPP).keepXMPPAlive(0x965921e0)
	/home/pi/go/src/github.com/google/cups-connector/xmpp/xmpp.go:132 +0x208
created by github.com/google/cups-connector/xmpp.(*XMPP).startXMPP
	/home/pi/go/src/github.com/google/cups-connector/xmpp/xmpp.go:113 +0x2a4
```

For now, I'm using a cronjob that kick-restarts `connector` every hour.

**Comment by jacobmarble** [comment] 2015-08-11 05:35
I really do not like XMPP. Keeping an XMPP conversation open with a slow, unreliable connection is going to be hard. Also, are you printing multi-megabyte documents through this pinhole? That must be shaky as well?

What if we added local printing, such that the cloud connection is optional? This means that you could turn off the entire conversation with the Google cloud; [printer sharing and print jobs would be scoped to the local subnet only](https://developers.google.com/cloud-print/docs/privet).

**Comment by mceachen** [comment] 2015-08-11 05:55
Local printing? Oh, YEAH!

It's seriously the only thing gimping chromebooks right now.

**Comment by jacobmarble** [comment] 2015-08-11 06:05
Then this is a duplicate of #6. I added a clarifying comment there.

**Closed by jacobmarble** 2015-08-11 06:05 UTC
