### ISSUE TITLE
Issue with state reporting on windows connector

### ISSUE THREAD

**Issue by Kasparas** [google/cups-connector#180] opened 2016-02-15 09:50 UTC
Windows DEV version connector reports every job as ABORTED, print job itself goes through.
Seems like an Issue with GetJobState fucn in Winspool.go (line 578)
Error leads to Windows Error code 87 (0x57).
Can it be an issue with OpenPrinter?

Adding console output.

2016-Feb-15 10:38:30 INFO [Job d871627f-b8e7-8969-a8d3-e018511a98ef] Received from cloud
2016-Feb-15 10:38:30 INFO [Job d871627f-b8e7-8969-a8d3e018511a98ef] Downloaded in 120.8194ms
2016-Feb-15 10:38:37 INFO [Job d871627f-b8e7-8969-a8d3-e018511a98ef] Submitted as native job 9
2016-Feb-15 10:38:51 INFO [Job d871627f-b8e7-8969-a8d3-e018511a98ef] State: ABORTED

**Comment by Kasparas** [comment] 2016-02-15 14:47
Follow up on issue.
I tracked it down to being caused by missing keep job alive flag from attributes in printer info.
When it was manually set in printer properties the print job went through. 
Looking at the possibility of setting attribute in printer through connector now.

**Comment by Kasparas** [comment] 2016-02-16 13:09
Fixed this issue.
Using "golang.org/x/sys/windows/registry" pck I change printer registry values that are related to printkeepprintedjob and then using
"golang.org/x/sys/windows/svc" package I control spooler service. 
Restart of spooler is required in order for changes in registry to take effect.
All of the registry changes are done at the very start of the connector main code.

**Comment by jacobmarble** [comment] 2016-02-16 18:11
Thanks for your research, I have seen the same bug. Is it possible to fix this with a job property rather than manipulating the registry and restarting the spooler? I would like the connector to "just work" as much as possible.

**Comment by Kasparas** [comment] 2016-02-16 19:23
It depends if it is possible to access attribute from PRINTER_INFO_2 this is where we have to set the byte to enable the setting. Also there has to be implemented method.
https://msdn.microsoft.com/en-us/library/windows/desktop/dd145082(v=vs.85).aspx
using it we can set option through spooler it self. I had troubles understanding how spooler setting accessed therefore I placed "band aid" on the issue.

**Comment by jacobmarble** [comment] 2016-02-18 00:40
Duplicate of #157

**Closed by jacobmarble** 2016-02-18 00:40 UTC
